notebook/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :notes
  # Defines the root path route ("/")
  root "notes#index"
end

notebook/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

notebook/app/models/note.rb
class Note < ApplicationRecord
  has_rich_text :content

  belongs_to :user
end

notebook/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
end

notebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

notebook/app/controllers/notes_controller.rb
class NotesController < ApplicationController
before_action :set_note, only: %i[show edit update destroy]
before_action :authenticate_user!
    def index
        @notes = Note.all
    end

    def show
    end

    def new
        @note = current_user.notes.build
    end

    def create
        @note = current_user.notes.build(note_params)
        respond_to do |format|
            if @note.save
                format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
            else
                format.html { render :new, status: :unprocessable_entity}
            end
        end
    end

    def edit
    end

    def update
        respond_to do |format|
            if @note.update(note_params)
                format.html { redirect_to note_url(@note), notice: "Note was successfully updated."}
            else
                format.html { render :edit, status: :unprocessable_entity}
            end
        end 
    end

    def destroy
        @note.destroy
        respond_to do |format|
            format.html { redirect_to notes_url, notice: "Note was successfully detroyed."}
        end
    end
    
    private

    def set_note
        @note = Note.find(params[:id])
    end

    def note_params
        params.require(:note).permit(:title, :content, :user_id)
    end
end

notebook/app/helpers/application_helper.rb
module ApplicationHelper
end

notebook/app/helpers/notes_helper.rb
module NotesHelper
end

notebook/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

notebook/app/views/notes/_form.html.erb
<%= form_with(model: note) do |form|%>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title, style: "display: block"%>
    </div>
    <div>
        <%= form.label :content%>
        <%= form.rich_text_area :content, style: "display: block"%>
    </div>
    <div>
        <%#= form.hidden_field :user_id, value: current_user.id %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

notebook/app/views/notes/_note.html.erb
<div id="<%= dom_id note%>">
<p><%= note.title %></p>
<p><%= note.content %></p>
</div>

notebook/app/views/notes/edit.html.erb
<h2> Edit Note </h2>
<%= render "form", note: @note%>

notebook/app/views/notes/index.html.erb
<h2> Notes </h2>
<div>
    <%= link_to "Cretae Note",new_note_path %>
</div>
<%= render @notes %>

notebook/app/views/notes/new.html.erb
<h2> Create new Notebook </h2>
<%= render "form", note: @note%>

notebook/app/views/notes/show.html.erb
<h1> Note </h1>
<%= link_to "New Note", new_note_path%>
<%= link_to "Show All Notes", notes_path%> 
<%= render @note%>
<%= button_to "Delete", note_path(@note), method: :delete%>