appointment/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "rooms#index"

  resources :rooms 
  resources :bookings
end

appointment/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

appointment/app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :room
    belongs_to :user
end

appointment/app/models/room.rb
class Room < ApplicationRecord
    validates :name, :capacity, presence: true
    has_many :bookings
end

appointment/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
end

appointment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

appointment/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_booking, only: %i[show edit update destroy]
before_action :authenticate_user!
    def index
        @bookings = Booking.all
    end

    def show

    end

    def new
        @booking = Booking.new
    end

    def create
        @booking = Booking.new(booking_params)
        respond_to do |format|
            if @booking.save
                format.html {redirect_to booking_url(@booking), notice: "Booking was successfully created."}
            else
                format.html {render :new, status: :unprocessable_entity}
            end
        end
    end

    def edit

    end

    def update
        respond_to do |format|
            if @booking.update(booking_params)
                format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated."}
            else
                format.html { render :edit, status: :unprocessable_entity}
            end
        end
    end

    def destroy
        @booking.destroy
        respond_to do |format|
            format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed."}
        end
    end

    private

    def set_booking
        @booking = Booking.find(params[:id])
    end

    def booking_params
        params.require(:booking).permit(:start, :end, :purpose, :room_id, :user_id)
    end
end

appointment/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
before_action :set_room, only: %i[show edit update destroy]
    def index
        @rooms = Room.all
    end

    def show 
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(room_params)
        respond_to do |format|
            if @room.save
                format.html{ redirect_to room_url(@room), notice: "Room was successfully created."}
            else
                format.html {render :new, status: :unprocessable_entity}
        
            end
        end
    end

    def edit
    
    end

    def update
        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to room_url(@room), notice: "Room was successfully updated."}
            else
                format.html { render :edit, status: :unprocessable_entity}
            end
        end
    end 

    def destroy
        @room.destroy
        respond_to do |format|
            format.html { redirect_to rooms_url, notice: "Room was successfully destroyed."}
        end
    end
    
    private

    def set_room    
        @room = Room.find(params[:id])
    end

    def room_params
        params.require(:room).permit(:name, :capacity)
    end
end

appointment/app/helpers/application_helper.rb
module ApplicationHelper
end

appointment/app/helpers/bookings_helper.rb
module BookingsHelper
end

appointment/app/helpers/rooms_helper.rb
module RoomsHelper
end

appointment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <p class="notice"><%= notice%></p>
  <p class="alert"><%= alert%></p>
  <% if user_signed_in?%>
  <%= link_to "Bookings", bookings_path%>
  <%= link_to "Rooms", rooms_path%>
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete%>
  <% else %>
    <%= link_to "Sign In", new_user_session_path%>
    <%= link_to "Sign Up", new_user_registration_path%>
  <% end %>
    <%= yield %>
  </body>
</html>

appointment/app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form|%>
    <% if room.errors.any? %>
        <div style= "color: red">
            <h2><%= pluralize(room.errors.count, "errors")%> prohibited this room from saving </h2>
            <ul>
            <% room.errors.each do |error|%>
            <li><%= error.full_message%></li>
            <% end %>
            </ul>
        </div>
    <% end %>
<div>
    <%= form.label :name, style: "display: block"%>
    <%= form.text_field :name%>
</div>

<div>
    <%= form.label :capacity, style: "display: block"%>
    <%= form.number_field :capacity%>
</div>

<div>
    <%= form.submit%>
</div>

<% end %>

appointment/app/views/rooms/edit.html.erb
<h2>Edit Room</h2>
<%= render "form", room: @room %>

appointment/app/views/rooms/index.html.erb
<h2>Rooms</h2>
<% @rooms.each do |room|%>
<p> Room:
<%= link_to room.name, room%>
</p>
<p> Capacity:
<%= room.capacity%>
</p>
<% end %>

<%= link_to "New Room", new_room_path%>

appointment/app/views/rooms/new.html.erb
<h1> New Room </h1>
<%= render 'form', room: @room%>

appointment/app/views/rooms/show.html.erb
<%= @room.name%>
<%= @room.capacity%>
<%= button_to "Delete", room_path, method: :delete%>

<% @room.bookings.each do |booking|%>
<p>Start: <%= booking.start%></p>
<p>End: <%= booking.end%></p>
<p>Purpose: <%= booking.purpose%></p>
<p><%= link_to "Booking", booking%></p>
<% end %>